"""Joke - Generate dad jokes (冷笑话) with a sense of humor.

Creates punny, cheesy dad jokes on any topic. So bad they're good.
"""

import argparse
import random
from datetime import datetime

from config import summarize, save_note, VAULT_PATH

PROMPT = """You are a master of dad jokes and 冷笑话 (cold jokes). Your specialty is puns, wordplay, and jokes so cheesy they make people groan — in a good way.

Generate ONE dad joke / 冷笑话 based on the topic or subject provided. The joke should:
- Be a classic dad joke style: setup → punchline with a pun or unexpected twist
- Be family-friendly
- Work in English (or Chinese if the topic is better suited)
- Be genuinely funny in a "so bad it's good" way

Output ONLY the joke itself — no preamble, no "Here's a joke:", no explanation. Just the joke.
If it has a setup and punchline, format as two lines or use "—" to separate.
"""

DEFAULT_TOPICS = [
    "programming", "coffee", "cats", "weather", "food", "exercise",
    "sleep", "AI", "books", "music", "travel", "Monday", "weekend",
    "shoes", "gardening", "math", "pizza", "rain", "socks",
]


def main():
    parser = argparse.ArgumentParser(
        description="Generate a dad joke (冷笑话) on any topic",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python3 _scripts/joke.py                    # Random topic
  python3 _scripts/joke.py "Python"           # Joke about Python
  python3 _scripts/joke.py "meetings" --save  # Save to vault
""",
    )
    parser.add_argument(
        "topic",
        type=str,
        nargs="?",
        default=None,
        help="Topic for the joke (e.g., coffee, programming). Random if omitted.",
    )
    parser.add_argument(
        "--save",
        action="store_true",
        help="Save joke to vault (Sources/Joke - YYYY-MM-DD.md)",
    )
    args = parser.parse_args()

    topic = args.topic or random.choice(DEFAULT_TOPICS)
    user_input = f"Topic: {topic}"

    print(f"Generating a dad joke about: {topic}...")
    joke = summarize(user_input, PROMPT)

    print()
    print("—" * 30)
    print(joke)
    print("—" * 30)

    if args.save:
        today = datetime.now().strftime("%Y-%m-%d")
        content = f"""# Dad Joke — {today}

**Topic:** {topic}

{joke}

---
*Generated by /skill joke*
"""
        save_note(f"Sources/Joke - {today}.md", content)


if __name__ == "__main__":
    main()
